"""empty message

Revision ID: 929fb40c9d46
Revises: 
Create Date: 2025-09-01 22:46:58.262990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '929fb40c9d46'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maceta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=255), nullable=False),
    sa.Column('precio', sa.Integer(), nullable=False),
    sa.Column('tamaño', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('contraseña', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('carrito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maceta_carrito',
    sa.Column('id_maceta_carrito', sa.Integer(), nullable=False),
    sa.Column('id_maceta', sa.Integer(), nullable=False),
    sa.Column('id_carrito', sa.Integer(), nullable=False),
    sa.Column('cantidad_maceta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_carrito'], ['carrito.id'], ),
    sa.ForeignKeyConstraint(['id_maceta'], ['maceta.id'], ),
    sa.PrimaryKeyConstraint('id_maceta_carrito')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maceta_carrito')
    op.drop_table('carrito')
    op.drop_table('usuario')
    op.drop_table('maceta')
    # ### end Alembic commands ###
