"""empty message

Revision ID: b5424747c7fc
Revises: 929fb40c9d46
Create Date: 2025-09-02 15:23:50.710854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5424747c7fc'
down_revision = '929fb40c9d46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maceta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maceta', schema=None) as batch_op:
        batch_op.drop_column('imagen')

    # ### end Alembic commands ###
